export const wordData = {
  // verbs
  verbTokenRegex: [
    "'m",
    "'s", // TODO: distinguish this from the possessive pronoun
    "'re"
  ],
  verbTokenMatch: ["am", "is", "are", "was", "were", "be", "been"],
  // nouns
  nounTokenRegex: [
    "ion",
    "ions",
    "ism",
    "isms",
    "ity",
    "ities",
    "ment",
    "ments",
    "ness",
    "ance",
    "ances",
    "ence",
    "ences"
  ],

  nounExceptionMatch: [
    "prism",
    "city",
    "audience",
    "million",
    "billion",
    "trillion", // lion, prion, zion, ion, Dion, lesion, mention, action...
    "science",
    "sciences",
    "audience",
    "audiences",
    "party", // pity
    "sentence",
    "sentences",
    "freelance"
  ],

  // adj/adv
  adjTokenRegex: ["ly", "al", "ent", "ive", "ous", "ful", "less", "ant", "ible", "able", "ic", "ary", "ac"],

  adjectiveAdverbExceptionMatch: [
    /*
          'agent',
          'ant',
          'aphrodisiac',
          'apothecary',
          'appeal',
          'apply',
          'bent',
          'cant',
          'cant',
          'cent',
          'content',
          'continent',
          'deal',
          'dent',
          'dictionary',
          'dive',
          'early',
          'fabric',
          'family',
          'five',
          'fly',
          'functionary',
          'gent',
          'give',
          'grant',
          'handful',
          'hive',
          'imply',
          'intent',
          'jive',
          'lent',
          'live',
          'logic',
          'magic',
          'maniac',
          'meant',
          'merchant',
          'monopoly',
          'mosaic',
          'mouth',
          'music',
          'nary',
          'north',
          'pant',
          'pant',
          'pent',
          'percent',
          'plant',
          'potential',
          'prevent',
          'rant',
          'relent',
          'rent',
          'rubric',
          'public',
          'rant',
          'secretary',
          'sent',
          'south',
          'spent',
          'stent',
          'student',
          'supply',
          'table',
          'teeth',
          'tent',
          'thrive',
          'tooth',
          'topiary',
          'trident',
          'unruly',
          'vary',
          'vent',
          'want',
          'want',
          'went',
          'with' */
    "not",
    "however",
    "only",
    "then",
    "also"
  ],

  // TODO: preposition check should exclude 'to' infinitives and compound prepositions
  prepositionTokenMatch: [
    "about",
    "above",
    "across",
    "after",
    "against",
    "along",
    "among",
    "around",
    "at",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "between",
    "beyond",
    "by",
    "down",
    "during",
    "for",
    "from",
    "in",
    "inside",
    "into",
    "near",
    "of",
    "off",
    "on",
    "onto",
    "out",
    "outside",
    "over",
    "past",
    "since",
    "through",
    "throughout",
    "till",
    "to",
    "toward",
    "under",
    "underneath",
    "until",
    "up",
    "upon",
    "with",
    "within",
    "without"
  ],

  // waste
  wasteWordTokenMatch: ["it", "this", "that", "there"]
};

// export class WordData {
//   // verbs
//   public static verbTokenRegex = [
//     "'m",
//     "'s", // TODO: distinguish this from the possessive pronoun
//     "'re"
//   ];

//   public static verbTokenMatch = ["am", "is", "are", "was", "were", "be", "been"];

//   // nouns
//   public static nounTokenRegex = [
//     "ion",
//     "ions",
//     "ism",
//     "isms",
//     "ity",
//     "ities",
//     "ment",
//     "ments",
//     "ness",
//     "ance",
//     "ances",
//     "ence",
//     "ences"
//   ];

//   public static nounExceptionMatch = [
//     "prism",
//     "city",
//     "audience",
//     "million",
//     "billion",
//     "trillion", // lion, prion, zion, ion, Dion, lesion, mention, action...
//     "science",
//     "sciences",
//     "audience",
//     "audiences",
//     "party", // pity
//     "sentence",
//     "sentences",
//     "freelance"
//   ];

//   // adj/adv
//   public static adjTokenRegex = [
//     "ly",
//     "al",
//     "ent",
//     "ive",
//     "ous",
//     "ful",
//     "less",
//     "ant",
//     "ible",
//     "able",
//     "ic",
//     "ary",
//     "ac"
//   ];

//   public static adjectiveAdverbExceptionMatch = [
//     /*
//           'agent',
//           'ant',
//           'aphrodisiac',
//           'apothecary',
//           'appeal',
//           'apply',
//           'bent',
//           'cant',
//           'cant',
//           'cent',
//           'content',
//           'continent',
//           'deal',
//           'dent',
//           'dictionary',
//           'dive',
//           'early',
//           'fabric',
//           'family',
//           'five',
//           'fly',
//           'functionary',
//           'gent',
//           'give',
//           'grant',
//           'handful',
//           'hive',
//           'imply',
//           'intent',
//           'jive',
//           'lent',
//           'live',
//           'logic',
//           'magic',
//           'maniac',
//           'meant',
//           'merchant',
//           'monopoly',
//           'mosaic',
//           'mouth',
//           'music',
//           'nary',
//           'north',
//           'pant',
//           'pant',
//           'pent',
//           'percent',
//           'plant',
//           'potential',
//           'prevent',
//           'rant',
//           'relent',
//           'rent',
//           'rubric',
//           'public',
//           'rant',
//           'secretary',
//           'sent',
//           'south',
//           'spent',
//           'stent',
//           'student',
//           'supply',
//           'table',
//           'teeth',
//           'tent',
//           'thrive',
//           'tooth',
//           'topiary',
//           'trident',
//           'unruly',
//           'vary',
//           'vent',
//           'want',
//           'want',
//           'went',
//           'with' */
//     "not",
//     "however",
//     "only",
//     "then",
//     "also"
//   ];

//   // TODO: preposition check should exclude 'to' infinitives and compound prepositions
//   public static prepositionTokenMatch = [
//     "about",
//     "above",
//     "across",
//     "after",
//     "against",
//     "along",
//     "among",
//     "around",
//     "at",
//     "before",
//     "behind",
//     "below",
//     "beneath",
//     "beside",
//     "between",
//     "beyond",
//     "by",
//     "down",
//     "during",
//     "for",
//     "from",
//     "in",
//     "inside",
//     "into",
//     "near",
//     "of",
//     "off",
//     "on",
//     "onto",
//     "out",
//     "outside",
//     "over",
//     "past",
//     "since",
//     "through",
//     "throughout",
//     "till",
//     "to",
//     "toward",
//     "under",
//     "underneath",
//     "until",
//     "up",
//     "upon",
//     "with",
//     "within",
//     "without"
//   ];

//   // waste
//   public static wasteWordTokenMatch = ["it", "this", "that", "there"];
// }
